refresh_time: 3

# send email interval (minutes)
email_interval: 5

# ping time limits
connection:
  "interia.pl":
    time: 10.00
  "onet.pl":
    time: 20

# directories size limits
directories:
  "carer/":
    size: 65
  "config/":
    size: 3

# minimum memory in M
memory:
  "memory":
    minimum: 20


# CUSTOM CHECK! checks if seconds in system time are less than 30
custom:
  "system_seconds_less_than_30":
    target_value: '`date`.split(" ")[3].split(":").last.to_i'
    comparator: "<"
    value: 30
